### ISSUE TITLE
LEAPP

### ISSUE THREAD

**Issue by upintheairsheep** [kninami/conversational-ai-forensic#1]
Hello, could you incorporate these scripts as part as the LEAPP projects at https://github.com/abrignoni , as well as including mobile artifacts? LEAPP programs are bundled with a few popular and commercial programs, so it’s important for this info not be fragmented and obscured from the investigators that will tackle crimes (mainly malware and scams)

**Comment by kninami** [comment]
Thank you for your interest in my project. I wanted to ask for clarification—are you officially involved with the LEAPP project, and is this an official proposal from the LEAPP team?

**Comment by upintheairsheep** [comment]
No, I am just suggesting, I am not involved with the project officially, I
am just here to request.

**Comment by kninami** [comment]
Thank you for the great suggestions. I will consider it.
